/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/prod/full_hearth.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.heart.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.5, 0.5, 0.5]}
      />
      <mesh geometry={nodes.top.geometry} material={nodes.top.material} position={[-0.72, 1.25, -0.1]} />
      <mesh
        geometry={nodes.low.geometry}
        material={nodes.low.material}
        position={[-0.59, -1.01, -0.5]}
        rotation={[0.23, -0.03, -0.07]}
        scale={[1.17, 1.17, 1.17]}
      />
      <mesh geometry={nodes['1'].geometry} material={nodes['1'].material} position={[1.12, 0.49, 0]} />
      <mesh geometry={nodes['2'].geometry} material={nodes['2'].material} position={[-2.26, 0, 0]} />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0.18, -0.51, 0.33]}
        scale={[0.96, 0.39, 1.48]}
      />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.06, 0.24, -0.06]} />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-0.06, 0.07, -0.06]}
        scale={[1.25, 0.6, 1.25]}
      />
      <mesh geometry={nodes.blod2.geometry} material={nodes.blod2.material} position={[0, 0, 0.11]} />
      <mesh geometry={nodes.bloodB1.geometry} material={nodes.bloodB1.material} position={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/prod/full_hearth.gltf')
