/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { Html, useGLTF } from "@react-three/drei";
import styled from "styled-components";

export default function Heart(props) {
  const group = useRef();
  const [hidden, set] = useState();
  // eslint-disable-next-line no-unused-vars
  const { nodes, materials } = useGLTF("/prod/3dheart.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Atop.geometry}
        material={nodes.Atop.material}
        position={[-0.72, 1.19, -0.1]}
      />
      {/* LCA */}
      <mesh
        geometry={nodes.Abottom.geometry}
        material={nodes.Abottom.material}
        position={[-0.59, -1.01, -0.5]}
        rotation={[0.23, -0.03, -0.07]}
        scale={[1.17, 1.17, 1.17]}
      ></mesh>
      {/* LCX */}
      <mesh
        geometry={nodes.Rmain.geometry}
        material={nodes.Rmain.material}
        position={[1.12, 0.49, 0]}
      >
      </mesh>
      {/* PDA */}
      <mesh
        geometry={nodes.Lmain.geometry}
        material={nodes.Lmain.material}
        position={[0, 0, 1.69]}
      ></mesh>
      {/* PL */}
      <mesh
        geometry={nodes.Rbig.geometry}
        material={nodes.Rbig.material}
        position={[0, 0, 1.5]}
      ></mesh>
      {/* Septal */}
      <mesh
        geometry={nodes.Rsmall1.geometry}
        material={nodes.Rsmall1.material}
        position={[-0.05, -0.34, 0.3]}
      ></mesh>
      {/* Diagonal */}
      <mesh
        geometry={nodes.Rsmall2.geometry}
        material={nodes.Rsmall2.material}
        position={[-0.08, -0.32, 2.13]}
      ></mesh>
      <mesh
        geometry={nodes.BezierCurve007.geometry}
        material={nodes.BezierCurve007.material}
        position={[0.67, -1.6, 0.71]}
      />
      <mesh
        geometry={nodes.BezierCurve008.geometry}
        material={nodes.BezierCurve008.material}
        position={[0.67, -1.6, 0.71]}
      />
      <mesh
        geometry={nodes.BezierCurve009.geometry}
        material={nodes.BezierCurve009.material}
        position={[0.67, -1.6, 0.71]}
      />
      <mesh
        geometry={nodes.BezierCurve010.geometry}
        material={nodes.BezierCurve010.material}
        position={[1.15, -1.33, 0.22]}
      />
      <mesh
        geometry={nodes.BezierCurve011.geometry}
        material={nodes.BezierCurve011.material}
        position={[1.15, -1.33, 0.22]}
      />
      <mesh
        geometry={nodes.BezierCurve012.geometry}
        material={nodes.BezierCurve012.material}
        position={[1.15, -1.33, 0.22]}
      />
    </group>
  );
}

const StyledDiv = styled.div`
  padding-top: 10px;
  transform: translate3d(50%, 0, 0);
  text-align: left;
  background: #202035;
  color: white;
  padding: 10px 15px;
  border-radius: 5px;
  cursor: pointer;
  transition: all 0.5s;

  &:hover {
    opacity: 0.9;
    transform-origin: center;
    transform: scale(1.25);
  }

  &:active {
    opacity: 0.7;
  }
`;

useGLTF.preload("/prod/3dheart.gltf");
