/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Human(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/prod/3dhuman.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Low_Poly_Characte000.geometry}
        material={materials['Material.002']}
        position={[0, 3.04, 0]}
      />
    </group>
  )
}

useGLTF.preload('/prod/3dhuman.gltf')
