/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { Div1 } from "./styles";

export default function Model(props) {
  const group = useRef();
  const rca = useRef();
  const lad = useRef();
  const lm = useRef();
  const lcx = useRef();
  const om = useRef();
  const septal = useRef();
  const diagonal1 = useRef();
  const diagonal2 = useRef();
  const diagonal3 = useRef();
  const rma = useRef();
  const pda = useRef();
  const pl = useRef();
  const { nodes, materials } = useGLTF("/prod/newRightHeart.gltf");
  const red = materials.red.color;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.RCA.geometry} position={[1.12, 0.49, 0]} ref={rca}>
        <meshPhongMaterial color={red} />
        <Html position={[-1.6, -0.49, 0.85]} zIndexRange={[900, 0]}>
          <Div1
            content="RCA"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([rca])}
            onMouseLeave={() => props.onHover(null)}
          >
            5
          </Div1>
        </Html>
      </mesh>
      <mesh geometry={nodes.LAD.geometry} position={[0, 0, 1.5]} ref={lad}>
        <meshPhongMaterial color={red} />
        <Html position={[0.6, 0.2, -0.85]} zIndexRange={[900, 0]}>
          <Div1
            content="LAD"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([lad])}
            onMouseLeave={() => props.onHover(null)}
          >
            3
          </Div1>
        </Html>
      </mesh>
      <group>
        <mesh
          geometry={nodes.Rsmall2.geometry}
          position={[-0.04, 0.07, 1.92]}
          ref={diagonal1}
        >
          <meshPhongMaterial color={red} />
          <Html position={[1.3, -0.55, -1.35]} zIndexRange={[900, 0]}>
            <Div1
              content="Diagonal"
              onClick={props.handleClick}
              onMouseEnter={() =>
                props.onHover([diagonal1, diagonal2, diagonal3])
              }
              onMouseLeave={() => props.onHover(null)}
            >
              9
            </Div1>
          </Html>
          <Html position={[1.2, -0.7, -1.1]} zIndexRange={[900, 0]}>
            <Div1
              content="Diagonal"
              onClick={props.handleClick}
              onMouseEnter={() =>
                props.onHover([diagonal1, diagonal2, diagonal3])
              }
              onMouseLeave={() => props.onHover(null)}
            >
              9
            </Div1>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.Rsmall2002.geometry}
          position={[-0.31, -0.89, 2.28]}
          ref={diagonal2}
        >
          <meshPhongMaterial color={red} />
          <Html position={[1.25, -0.37, -1.2]} zIndexRange={[900, 0]}>
            <Div1
              content="Diagonal"
              onClick={props.handleClick}
              onMouseEnter={() =>
                props.onHover([diagonal1, diagonal2, diagonal3])
              }
              onMouseLeave={() => props.onHover(null)}
            >
              9
            </Div1>
          </Html>
        </mesh>
        <mesh
          geometry={nodes.Rsmall2003.geometry}
          position={[-0.31, -0.29, 2.24]}
          ref={diagonal3}
        >
          <meshPhongMaterial color={red} />
          <Html position={[1.35, -0.5, -1.25]} zIndexRange={[900, 0]}>
            <Div1
              content="Diagonal"
              onClick={props.handleClick}
              onMouseEnter={() =>
                props.onHover([diagonal1, diagonal2, diagonal3])
              }
              onMouseLeave={() => props.onHover(null)}
            >
              9
            </Div1>
          </Html>
        </mesh>
      </group>
      <mesh
        geometry={nodes.septal.geometry}
        position={[-1.36, 0.05, 0.7]}
        ref={septal}
      >
        <meshPhongMaterial color={red} />
        <Html position={[1.85, -0.5, 0.5]} zIndexRange={[900, 0]}>
          <Div1
            content="Septal"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([septal])}
            onMouseLeave={() => props.onHover(null)}
          >
            4
          </Div1>
        </Html>
      </mesh>

      <mesh
        geometry={nodes.aorta_new.geometry}
        material={nodes.aorta_new.material}
        position={[0.67, 0.06, 0.71]}
      />
      <mesh
        geometry={nodes.RMA.geometry}
        position={[-1.52, -0.47, 1.07]}
        ref={rma}
      >
        <meshPhongMaterial color={red} />
        <Html position={[1.0, -0.35, -0.1]} zIndexRange={[900, 0]}>
          <Div1
            content="RMA"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([rma])}
            onMouseLeave={() => props.onHover(null)}
          >
            6
          </Div1>
        </Html>
      </mesh>
      <mesh
        geometry={nodes.middleTiny2.geometry}
        position={[1.68, -1.95, 0.88]}
        ref={pda}
      >
        <meshPhongMaterial color={red} />
        <Html position={[-1.8, 1, -0.71]} zIndexRange={[900, 0]}>
          <Div1
            content="PDA"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([pda])}
            onMouseLeave={() => props.onHover(null)}
          >
            7
          </Div1>
        </Html>
      </mesh>
      <mesh
        geometry={nodes.Rbig2.geometry}
        position={[0.12, -0.39, 0.33]}
        ref={om}
      >
        <meshPhongMaterial color={red} />
        <Html position={[0.9, -0.2, -0.55]} zIndexRange={[900, 0]}>
          <Div1
            content="OM"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([om])}
            onMouseLeave={() => props.onHover(null)}
          >
            10
          </Div1>
        </Html>
      </mesh>

      <mesh geometry={nodes.LM.geometry} position={[1.12, 0.49, 0]} ref={lm}>
        <meshPhongMaterial color={red} />
        <Html position={[-0.8, 0, 0.3]} zIndexRange={[900, 0]}>
          <Div1
            content="LM"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([lm])}
            onMouseLeave={() => props.onHover(null)}
          >
            1
          </Div1>
        </Html>
      </mesh>
      <mesh
        geometry={nodes.LCx.geometry}
        material={nodes.LCx.material}
        position={[1.12, 0.49, 0]}
        ref={lcx}
      >
        <Html position={[-0.25, -0.49, 0]} zIndexRange={[900, 0]}>
          <Div1
            content="LCx"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([lcx])}
            onMouseLeave={() => props.onHover(null)}
          >
            2
          </Div1>
        </Html>
      </mesh>
      <mesh
        geometry={nodes.PL.geometry}
        material={nodes.PL.material}
        position={[1.12, 0.49, 0]}
        ref={pl}
      >
        <Html position={[-1.1, -1.25, -0.1]} zIndexRange={[900, 0]}>
          <Div1
            content="PL"
            onClick={props.handleClick}
            onMouseEnter={() => props.onHover([pl])}
            onMouseLeave={() => props.onHover(null)}
          >
            8
          </Div1>
        </Html>
      </mesh>
    </group>
  );
}

useGLTF.preload("/prod/newRightHeart.gltf");
